# Global parameters for all sims
# All units are in pixels and discrete time iterations. Angles are as a proportion of pi.

world:
  sim_time: 1000
  screen_size: 500
  grid_num: 25

robot:
  num_robots: 20
  robot_vel: 4.
  lim_distance: 200
  lim_angle: 0.5
  angle_incr: 0.1
  rep_range: 0
  rep_factor: 3
  split: 0.5
  stimscale: 2.0
  influence_scale: 2.5
  noise_factor: 0.00138888
